AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'sam-simple-db

  Simple API for storing and retrieving json data on S3

  '
Globals:
  Function:
    Timeout: 3
Metadata:
  AWS::ServerlessRepo::Application:
    Name: moblybird-simple-db
    Description: Function to store and retrieve simple data
    Author: Wouter
    License: license.txt
    ReadmeUrl: s3://moblybird-sam-files/c2524af8aba435aaeb578be7a6fecb1e
    Labels:
    - Simple
    - Database
    SemanticVersion: 0.0.1
Resources:
  MoblybirdSimpleDbFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://moblybird-sam-files/32cf1d5bc3c89b394caa2743da161281
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        Endpoint1:
          Type: Api
          Properties:
            Path: /simpledb/{filename}/{id}
            Method: any
        Endpoint2:
          Type: Api
          Properties:
            Path: /simpledb/{filename}
            Method: any
Outputs:
  MoblybirdSimpleDbApi:
    Description: API Gateway endpoint URL for Prod stage for MoblybirdSimpleDbFunction
      function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/simpledb/
  MoblybirdSimpleDbFunction:
    Description: MoblybirdSimpleDb Lambda Function ARN
    Value:
      Fn::GetAtt:
      - MoblybirdSimpleDbFunction
      - Arn
  MoblybirdSimpleDbFunctionIamRole:
    Description: Implicit IAM Role created for MoblybirdSimpleDb function
    Value:
      Fn::GetAtt:
      - MoblybirdSimpleDbFunctionRole
      - Arn
